name: trigger_deploy
on:
  repository_dispatch:
  push:
    branches:
      - staging
      - github-action-deploy-by-branchname
jobs:
  deploy-remote-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Trigger Deploy - Dispatch initiating repository event for infrastructure repo to trigger a deployment
        if: github.event.action != 'deploy_successful'
        run: |
          curl -X POST https://api.github.com/repos/DigitalCareerInstitute/infrastructure/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "trigger_deploy", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "branch_name": "'"$GIT_BRANCH_NAME"'"  }}'
      - name: ACK Telegram - Acknowledge deploy_successful from remote infrastructure repository
        if: github.event.action == 'deploy_successful'
        run: |
          curl -s -X POST https://api.telegram.org/${{secrets.TELEGRAM_BOT_ID}}/sendMessage \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -d chat_id=${{ secrets.TELEGRAM_BOT_CHAT_ID }} \
          -d text="Deploy of 'marketing-website' $GIT_BRANCH_NAME $GITHUB_SHA on $(date) successful"
      - name: ACK Slack - Acknowledge deploy_successful from remote infrastructure repository
        # TODO notify on master deploys
        # if: github.event.action == 'deploy_successful' && ${{ env.GIT_BRANCH_NAME == 'master'}}
        if: github.event.action == 'deploy_successful' 
        run: |
           curl -X POST https://hooks.slack.com/services/${{secrets.SLACK_WEBHOOK}} \
           -H 'Content-type: application/json' \
           --data "{'text':'Deploy of marketing-website ${{ github.event.client_payload.branch_name }} $GITHUB_SHA on $(date) successful'}"

